[build]
  command = "hugo --gc --minify -b $URL"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.58.1"
  HUGO_ENABLEGITINFO = "true"

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

# These rules will change if you change your site’s custom domains or HTTPS settings

# Redirect domain aliases to primary domain
https://www.alexjmazursky.com/* https://www.alexmazursky.com/:splat 301!

# Optional: Redirect default Netlify subdomain to primary domain
https://alexmazursky.netlify.com/* https://www.alexmazursky.com/:splat 301!